name: 'coverage'
on:
  pull_request:
    branches: [ main2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install

    - name: Run Jest Tests
      env:
            # Set the JEST_FAKE_SHADOW environment variable to enable the
              # fake shadow root mode in Jest.
            JEST_FAKE_SHADOW: 1
      run: npm run test loginFrom.test
    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
          name: coverage
          path: coverage/
