name: PMD Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  pmd-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Download PMD
        run: wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.40.0/pmd-bin-6.40.0.zip && unzip pmd-bin-6.40.0.zip

      - name: Run PMD
        run: |
          ./pmd-bin-6.40.0/bin/run.sh pmd \
            -d ./src \
            -R pmd/ruleset.xml \
            -f csv \
            -reportfile pmd/pmd-report.csv

      - name: Upload PMD artifact
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: pmd/pmd-report.csv
